[package]
name = "tempfile-istream"
version = "0.1.0"
edition = "2021"
description = "Implement IStream on an exclusive temp file which is deleted on release"
repository = "https://github.com/wravery/tempfile-istream"
license = "MIT"
categories = [ "os::windows-apis" ]

[dependencies]
windows-implement = "0.32.0"
tempfile = "3.3.0"

[dependencies.windows]
version = "0.32.0"
features = [
    "alloc",
    "implement",
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_System_Com",
    "Win32_System_Com_StructuredStorage",
    "Win32_System_Ole",
    "Win32_System_Time",
    "Win32_UI_Shell",
]